version: "3.9"
services:
  app:
    container_name: bot
    image: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_IDENTITY=${BOT_IDENTITY}
      - BOT_CONTEXT_LENGTH=${BOT_CONTEXT_LENGTH}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - OPENAI_APIKEY=${OPENAI_APIKEY}
  db:
    image: mongo:5.0.6
    container_name: bot-db
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=${DB_PORT}
    volumes:
      - ./database:/database
