version: "3.9"
services:
  app:
    container_name: bot
    image: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_IDENTITY=${BOT_IDENTITY}
      - BOT_CONTEXT_LENGTH=${BOT_CONTEXT_LENGTH}
      - DISCORD_TOKEN=NDkyMjY3ODc4NDE1MDczMjgx.GzgJB2.B4riHdEvpK7xNZ7IuWGa0onjlqQkXfGjX-1K60
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_TOKEN_LIMIT=${OPENAI_TOKEN_LIMIT}