version: "3.9"
services:
  app:
    container_name: bot
    image: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_TOKEN_LIMIT=${OPENAI_TOKEN_LIMIT}
    env_file:
      - .env.prod